name: Kotarica
description: Kupujte sveže domaće proizvode.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^1.2.3
  web_socket_channel: ^1.1.0
  http: ^0.12.1
  provider: ^4.1.3
  image_picker: ^0.6.7+11
  image_picker_web: ^2.0.2
  path_provider: ^2.0.1
  flutter_svg: ^0.19.3
  cupertino_icons: ^1.0.2
  rate_my_app: ^0.4.0
  flutter_search_bar: ^2.1.0
  sticky_headers: "^0.1.8"
  carousel_slider: ^3.0.0
  fraction: ^2.0.1
  progress_indicators: ^0.1.5
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  js: ^0.6.2
  shared_preferences: ^0.5.3
  flutter_launcher_icons: ^0.7.4
  numberpicker: ^2.1.1
  mailer: ^5.0.0
  google_sign_in: ^5.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - src/abis/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Bold.otf
          weight: 900
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Medium.otf
          weight: 700
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 900
flutter_icons:
  image_path: "assets/icons/Icon.png"
  android: true
  ios: true
